version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /home/nuc/home_automation:/config
      - /etc/letsencrypt:/etc/letsencrypt
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - TZ=America/Los_Angeles
    restart: always
    network_mode: host
    ports:
      - "443:443"
      - "80:80"